source "https://github.com/CocoaPods/Old-Specs"
source 'git@bitbucket.org:dev-ennova/ios-podspecs.git'
platform :ios, '8.0'
use_frameworks!
 
target ‘Yoox’ do
 
 pod 'RxSwift'
 pod 'RxCocoa'
 pod 'Moya', '~> 7.0'
 pod 'Moya/RxSwift'
 pod 'Moya-ModelMapper/RxSwift'
 pod 'ModelMapper', '~> 2.1'
 pod 'RxOptional', '~> 2.0.0'
 pod 'AnyObjectConvertible'
 pod 'SDWebImage'

end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
